<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.e48kRht' shared service.

return $this->privates['.service_locator.e48kRht'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'repoSelection' => ['privates', 'App\\Repository\\SelectionRepository', 'getSelectionRepositoryService.php', true],
    'selection' => ['privates', '.errored..service_locator.e48kRht.App\\Entity\\Selection', NULL, 'Cannot autowire service ".service_locator.e48kRht": it references class "App\\Entity\\Selection" but no such service exists.'],
], [
    'manager' => '?',
    'repoSelection' => 'App\\Repository\\SelectionRepository',
    'selection' => 'App\\Entity\\Selection',
]);
