<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'karser_recaptcha3.form.type' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/karser/karser-recaptcha3-bundle/Form/Recaptcha3Type.php';

return $this->privates['karser_recaptcha3.form.type'] = new \Karser\Recaptcha3Bundle\Form\Recaptcha3Type('6Lc4d6IUAAAAAGW_lsPY0IF9522PRnFDhuXYs-7O', true);
