<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0t9BoBU' shared service.

return $this->privates['.service_locator.0t9BoBU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'candidate' => ['privates', '.errored..service_locator.0t9BoBU.App\\Entity\\Candidate', NULL, 'Cannot autowire service ".service_locator.0t9BoBU": it references class "App\\Entity\\Candidate" but no such service exists.'],
    'candidateRepo' => ['privates', 'App\\Repository\\CandidateRepository', 'getCandidateRepositoryService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'candidate' => 'App\\Entity\\Candidate',
    'candidateRepo' => 'App\\Repository\\CandidateRepository',
    'manager' => '?',
]);
