<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bPrejGg' shared service.

return $this->privates['.service_locator.bPrejGg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'selection' => ['privates', '.errored..service_locator.bPrejGg.App\\Entity\\Selection', NULL, 'Cannot autowire service ".service_locator.bPrejGg": it references class "App\\Entity\\Selection" but no such service exists.'],
], [
    'selection' => 'App\\Entity\\Selection',
]);
